<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <DevelopmentDependency>true</DevelopmentDependency>
    <MajorVersion>0</MajorVersion>
    <MinorVersion>1</MinorVersion>
    <PatchVersion>0</PatchVersion>
    <BuildNumber Condition="'$(BuildNumber)' == ''">0</BuildNumber>
    <Version>$(MajorVersion).$(MinorVersion).$(PatchVersion).0</Version>
    <FileVersion>$(MajorVersion).$(MinorVersion).$(PatchVersion).$(BuildNumber)</FileVersion>
    <Authors>Lars Iversen, Morten Hartlev Lindhart</Authors>
    <Copyright>Copyright $([System.DateTime]::UtcNow.ToString(yyyy)) (c) Morten Hartlev Lindhart. All rights reserved.</Copyright>
    <Description>Roslyn analyzers that enforce restrictions on dependencies between namespaces.</Description>
    <PackageId>Lindhart.DependencyCop</PackageId>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>Lindhart.DependencyCop;Roslyn;Analyzers;CodeAnalysis</PackageTags>
    <PackageProjectUrl>https://github.com/ykoksen/DependencyCop</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageVersion>$(MajorVersion).$(MinorVersion).$(PatchVersion)</PackageVersion>
    <RepositoryUrl>https://github.com/ykoksen/DependencyCop.git </RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);_AddAnalyzersToOutput</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="README.md">
      <PackagePath>\</PackagePath>
      <Pack>true</Pack>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="tools\*.ps1" CopyToOutputDirectory="PreserveNewest" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE" Link="LICENSE">
      <PackagePath></PackagePath>
      <Pack>true</Pack>
    </None>
    <ProjectReference Include="..\Lindhart.DependencyCop.CodeFixes\Lindhart.DependencyCop.CodeFixes.csproj" />
    <ProjectReference Include="..\Lindhart.DependencyCop\Lindhart.DependencyCop.csproj" />
    <None Update="Icon.png">
      <PackagePath></PackagePath>
      <Pack>true</Pack>
    </None>
  </ItemGroup>

  <Target Name="_AddAnalyzersToOutput">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(OutputPath)\Lindhart.DependencyCop.dll" PackagePath="analyzers/dotnet/cs" />
      <TfmSpecificPackageFile Include="$(OutputPath)\Lindhart.DependencyCop.CodeFixes.dll" PackagePath="analyzers/dotnet/cs" />
    </ItemGroup>
  </Target>

</Project>
